project:
  type: book
  output-dir: docs


book:
  title: "Webmaps"
  author: "Robin Kohrs"
  date: "1/21/2023"
  chapters:
    - index.qmd
    - mapbox.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

